### ISSUE TITLE
Spaces between digits ignored

### ISSUE THREAD

**Issue by jclehner** [BorysLevytskyi/BitwiseCmd#3]
When entering an expression like `2048 1 << 1` I'd expect it to be split into two tokens: `2048` and `1 << 1`, with the result being the same as if I had entered `2048 2`. Instead, the result is interpreted as `20481 << 1`.

**Comment by BorysLevytskyi** [comment]
BitwiseCmd supports either expression or list of numbers. Can't be both at the same time.
