### ISSUE TITLE
Multiplication doesn't work

### ISSUE THREAD

**Issue by BohdanM-AVISPL** [BorysLevytskyi/BitwiseCmd#38]
Inputs like `2*3` or `0x0000040810204081 * 127` leads to error: `¯\_(ツ)_/¯ Sorry, i don′t know what 2*3 is`

**Comment by BorysLevytskyi** [comment]
Hi, BohdanM. Thank you for taking the time to create this issue. This is by design. I do not indent BitwiseCmd to support all math operations. Currently, the app is in maintenance mode and as of now I don't have plans to work on it.

**Comment by BorysLevytskyi** [comment]
well, I said that and then spend almost a week rewriting parts of it. I think I eventually will add other operations. But now I'm having some problems figuring how it should all look like in terms of UI...
