### ISSUE TITLE
Is it possible to enter binary numbers?

### ISSUE THREAD

**Issue by hamoid** [BorysLevytskyi/BitwiseCmd#4]
0xFF works, but 0b0011 doesn't.

Is there a way?

**Comment by BorysLevytskyi** [comment]
Not right now. BitwiseCmd doesn't support binary format of numbers.

**Comment by hamoid** [comment]
So this could be a feature request then :)

I wanted to explain to someone bitwise operations, but it's hard to explain if I must enter the numbers in decimal, but the operations happen in binary.

**Comment by BorysLevytskyi** [comment]
I was in the process of moving BitwiseCmd to React. This will be second on my list. Thanks for the suggestion.

**Comment by BorysLevytskyi** [comment]
The feature was implemented, @hamoid. Enjoy it!

**Comment by hamoid** [comment]
Very nice!!! Thank you :)
