### ISSUE TITLE
Feature request: allow to set operation in URL

### ISSUE THREAD

**Issue by hamoid** [BorysLevytskyi/BitwiseCmd#7]
It would be great to be able to tweet operations as a URL, like http://bitwisecmd.com?0b111100&0b001111

What is not clear is if "&" would work, or it has to be replaced with AND or \\& or something else valid in a URL.

**Comment by BorysLevytskyi** [comment]
It's already working. There is # link near each input. Check it out http://bitwisecmd.com/#0b111100&0b001111

**Comment by hamoid** [comment]
Awesome! Perfect for discussing computer math online :)
